### ISSUE TITLE
更新時にエラーになる

### ISSUE THREAD

**Issue by YoshihiroIto** [Shougo/dein.vim#10]
# Problems summary

## Environment Information
 * OS: Windows10
 * Vim version: GVim 7.4 p1194 kaoriya 　

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible

let s:cache_dir = expand('~/.cache')
let s:vim_plugin_toml = expand('~/mini_vim_plugin.toml')

execute 'set runtimepath^=' . s:cache_dir . '/plugin/repos/github.com/Shougo/dein.vim'

call dein#begin(s:cache_dir . '/plugin')

if dein#load_cache([$MYVIMRC, s:vim_plugin_toml])
  call dein#add('Shougo/dein.vim')
  call dein#load_toml(s:vim_plugin_toml)
  call dein#save_cache()
endif

call dein#end()

filetype plugin indent on
```

```toml
[[plugins]]
repo      = 'Shougo/vimproc'
lazy      = 0

[[plugins]]
repo      = 'Shougo/tabpagebuffer.vim'
lazy      = 1
on_path   = '.*'
```

## The reproduce ways from Vim starting (Required!)
それぞれ

~/.mini_vimrc
~/mini_vim_plugin.toml

で保存時 ```gvim -u ~/.minivimrc```

```
:call  dein#update()
```
を行い更新する。
エラーになる。（スクリーンショット参照）

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/994125/13220128/aded68ce-d9b7-11e5-9bf9-f4a724088466.png)
