### ISSUE TITLE
Add on_OS option

### ISSUE THREAD

**Issue by pwntester** [Shougo/dein.vim#209]
This is an enhacement request, so sorry to not use the issue template.

I use some plugins that I want to enable on certain OSs. I would like to use the same vim config on all my OSs and was wondering if your could implement an on_OS option so you could load the plugin only for certain OSs. In a similar way I use has('macunix') on vimscript.

Thanks,
A

**Comment by Shougo** [comment]
It is not needed.  You can use `has()` instead.

**Comment by pwntester** [comment]
Nice, can you please provide an example in a dein.toml config file?

**Comment by Shougo** [comment]
Well...

```toml
[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = {n = '<Plug>'}
on_if = "has('win32')"
hook_add = 'nmap [Space]s  <Plug>(vimshell_switch)'
hook_source = 'source ~/.vim/rc/plugins/vimshell.rc.vim'
```
