### ISSUE TITLE
lazy plugin depends feature load order wrong

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#287]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I use your vim config.
I add to the `deinlazy.toml` file as follow:
```toml
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'mhinz/vim-startify'
depends = 'vim-devicons'
hook_source = '''
function! StartifyEntryFormat()
    return 'WebDevIconsGetFileTypeSymbol(absolute_path) ." ". entry_path'
endfunction
'''
```
And then I start gvim，run the command `Startify`, it show error like `Unknown function: WebDevIconsGetFileTypeSymbol`, I run `scriptnams`, then I know that `vim-devicons` load after `vim-startify`, then I run `Startify`, it can work.
