### ISSUE TITLE
How to load vim-devicons with denite when i lazyload them by dein

### ISSUE THREAD

**Issue by taigacute** [Shougo/dein.vim#342]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Hi，what  is the  correct order lazyload vim-devicons，denite？i use these plugins like lightline in dein.toml, startify denite defx in lazyload toml. now i can got the lightline startify ,defx works well with vim-devicons,but the denite cant work with vim-devicons.what should i do ?

## Expected
denite can work better with vim-devicons

## Environment Information (Required!)

 * dein.vim version(SHA1): the latest

 * OS: macos10.13.6

 * Vim/neovim version: neovim-0.4.0-dev

## Provide a minimal .vimrc with less than 50 lines (Required!)

```toml
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends='vim-devicons'
hook_source = '''
source ~/.config/nvim/core/plugins/denite.vim
source ~/.config/nvim/core/plugins/denite_menu.vim
'''
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add='''
let g:webdevicons_enable_denite = 1
'''

```

## The reproduce ways from Vim starting (Required!)

 1. use these settings in lazyload toml

## Screen shot (if possible)

N/A
## Upload the log messages by `:redir` and `:message` (if errored)
N/A
