### ISSUE TITLE
A plugin doesn't get saved by dein#save_rollback if `rev` is specified

### ISSUE THREAD

**Issue by Bannerets** [Shougo/dein.vim#383]
This is probably intended, but it would be useful to save the sha1 commit in a rollback file if the rev is a branch and not a specific commit, e.g:

```toml
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
```

[A check in the code](https://github.com/Shougo/dein.vim/blob/0c96f852f518465d89f99b57831cd09ecfbc6a18/autoload/dein/install.vim#L447)

#### Environment Information

 * dein.vim version(SHA1): 0c96f852f518465d89f99b57831cd09ecfbc6a18

 * Vim/neovim version: 0.4.4
