### ISSUE TITLE
Q: How to have plugin load conditions in TOML format?

### ISSUE THREAD

**Issue by hasufell** [Shougo/dein.vim#389]
Basically, I want to translate this into toml:

```vim
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
```
I know I can have conditionals in `build`, but I don't know how to make nvim-yarp and vim-hug-neovim-rpc only load in non-nvim in the toml file format.

**Comment by Shougo** [comment]
```toml
[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'
```

Note: `:UpdateRemotePlugins` is executed automatically in dein.vim
