### ISSUE TITLE
Feature/Question: hook_add_<filetype>

### ISSUE THREAD

**Issue by hasufell** [Shougo/dein.vim#392]
I want to add plugin configuration based on file type. I know there are a couple of ways to do that in `hook_add`, by explicitly checking the file type for example. But it always felt much cleaner to put such stuff into `.vim/after/ftplugin` directory. Could there be something like `hook_add_lua` to have the same semantics?

**Comment by Shougo** [comment]
You can use ftplugin feature like this.

```toml
[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['qf']
[plugins.ftplugin]
qf = '''
  nnoremap <buffer> r :<C-u>Qfreplace<CR>
'''
```
