### ISSUE TITLE
How can I correctly use on_map option in toml file?

### ISSUE THREAD

**Issue by krisfans** [Shougo/dein.vim#401]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
How to use `on_map` option in toml file? In `init.vim` I can use `nmap <space>/ <plug>NERDCommenterToggle`, but when in toml file ,what should I do?
## Expected
I use toml file manage my plugins , and I want to use a plug keymap in toml but failed.
For exmaple , I want to use  `<space>/` to comment a line with `nerdcommenter` plugin and use key `Enter` to use `<Plug>(EasyAlign)`
## Environment Information (Required!)

 * dein.vim version(SHA1):2.1

 * OS: windows 10 

 * Vim/neovim version: Nvim0.5

## Provide a minimal .vimrc with less than 50 lines (Required!)
my`init.vim`
```vim
" Your minimal .vimrc
t encoding=utf-8
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here like this:
  call dein#load_toml('~/AppData/Local/nvim/container/config/plugins.toml')
 " Add or remove your plugins here like this:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')
call dein#add('rakr/vim-one')
call dein#add('lifepillar/vim-solarized8')
  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable
" 颜色主题放在这里
colorscheme one
```
my `plugins.toml`

```toml
[[plugins]] # dein增强
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]] # 对齐
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>'
hook_add = '''
     vmap [Enter] <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/AppData/Local/nvim/container/plugin/defx.nvim.vim'

[[plugins]] # 注释插件
repo = 'scrooloose/nerdcommenter'
on_map = '<Plug>'
hook_add = '''
    nmap [Space]/ <plug>NERDCommenterToggle
    vmap [Space]/ <Plug>NERDCommenterToggle
'''

```
