### ISSUE TITLE
[Question] Introduction of nvim-treesitter

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/dein.vim#405]
# Question
I want to know how to write in a Toml file.
How can I write the following in a Toml file?
```vim
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
```

**Comment by Shougo** [comment]
```toml
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = 'all',
    highlight = {
        enable = true,
        disable = {},
    },
    ensure_installed = 'all',
}
EOF
'''
```

This is my config.
