### ISSUE TITLE
When denops.vim is set to depends, it doesn't work.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/dein.vim#439]
# Problems summary
When denops.vim is set to depends, it doesn't work.

## Expected
If you set denops.vim to depends, it works.

## Environment Information (Required!)

 * dein.vim version(SHA1): 134aa1c3c71efbec71bd0d7d790b84654f75ff71

 * OS: Mac

 * Vim/neovim version: NVIM v0.7.0-dev+914-g7717f38d3

## Provide a minimal .vimrc with less than 50 lines (Required!)

`init.vim`
```vim
if &compatible
    set nocompatible
endif
let $CACHE = expand('~/.cache')
if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif
let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))
call dein#load_toml('~/.config/nvim/dein/deinlazy.toml', {'lazy' : 1})
call dein#end()
call dein#save_state()

if has('vim_starting') && dein#check_install()
    call dein#install()
endif
```
`~/.config/nvim/dein/deinlazy.toml`
```toml
[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hook_source = '''
call ddu#custom#patch_global({
    \ 'ui': 'std',
    \ })
call ddu#custom#patch_global({
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \     },
    \   }
    \ })
'''
[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'
[[plugins]]
repo = 'Shougo/ddu-ui-std'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'
```

## The reproduce ways from Vim starting (Required!)

 1. Run command `Ddu -name=search file_rec -ui-param-startFilter=v:true`

## Screen shot (if possible)
![スクリーンショット 2022-01-24 21 54 55](https://user-images.githubusercontent.com/3197942/150786567-5e603951-b007-4512-a952-3653207b7688.png)
