### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/dein.vim#443]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When I do a delayed read of fuzzy-motion, it says there are no commands.

## Expected
Lazy loading of fuzzy-motion is possible.
By the way, if you enter the same command twice, it will succeed.

## Environment Information (Required!)

 * dein.vim version(SHA1): 137ec38f2316b7d973e89d7c2d4de46a9b73afdc

 * OS: Mac

 * Vim/neovim version: v0.7.0-dev+1039-g19b2ad051

## Provide a minimal .vimrc with less than 50 lines (Required!)

`init.vim`
```
if &compatible
    set nocompatible
endif

let $CACHE = expand('~/.cache')

if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif

let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))

call dein#load_toml('~/.config/nvim/dein/deinlazy.toml', { 'lazy': 1 })

call dein#end()
call dein#save_state()
```

`~/.config/nvim/dein/deinlazy.toml`
```toml
[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
depends = 'denops.vim'
on_cmd = 'FuzzyMotion'
```

## The reproduce ways from Vim starting (Required!)

 1. Start Neovim.
 2. Run `call dein#update()` command.
 3. Restart Neovim.
 4. Run `FuzzyMotion` command.

## Screen shot (if possible)
![スクリーンショット 2022-02-09 21 29 54](https://user-images.githubusercontent.com/3197942/153201367-abdd4512-a2d9-41b0-825d-ee79c277f519.png)

**Comment by Shougo** [comment]
It works for me.

```toml
[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
depends = 'denops.vim'
if = 'has("nvim")'
on_cmd = 'FuzzyMotion'
hook_add = '''
  nnoremap F   <Cmd>FuzzyMotion<CR>
'''
```

It is not problem of dein.
