### ISSUE TITLE
依存するプラグインが読みこまれていない時もプラグインが読みこまれてしまう

### ISSUE THREAD

**Issue by mirachan010** [Shougo/dein.vim#448]
**Warning: I will close the bug issue without the minimal init.vim and the
reproduce ways.**

# Problems summary

## Environment Information (Required!)

- dein.vim version(SHA1):9485e32

- OS:Windows11 Ubuntu(wsl) 両方で確認

- Vim/neovim version:8.2.4576

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:dein_dir = DEINPATH

set runtimepath^= DEINPATH

if dein#load_state(s:dein_dir)
  let s:dein_lazy_toml   = s:dein_dir . '01dein.toml'
  call dein#begin(s:dein_dir)
  call dein#load_toml(s:dein_lazy_toml, {'lazy': 1})
  call dein#end()
  call dein#save_state()
endif
if dein#check_install()
  call dein#install()
endif
let s:removed_plugins = dein#check_clean()
call dein#remote_plugins()

filetype plugin indent on
syntax enable
```
```toml
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
on_event = ['InsertEnter']
hook_add = '''
echo "ddc"
'''
[[plugins]]
repo = 'Shougo/pum.vim'
if='has("nvim")'
hook_add='''
echo "pum"
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
if = 'v:versionlong >= 8020624'
hook_add = '''
echo "denops"
```
## The reproduce ways from Vim starting (Required!)

1. 起動する
2. おとす
3. 起動する
4. pum.vimが起動しないためddcが起動しないはずなのにhook_addが読みこまれてしまう

## Screen shot (if possible)
上ではpum.vimのif='has("nvim")'を入れていないため読みこまれている。
下ではpum.vimはif='has("nvim")'により読みこまれていないが、ddc.vimが読みこまれてしまっている
![image](https://user-images.githubusercontent.com/37107329/159004053-36b30ab6-d38d-4d85-b4a1-8240c49fe39a.png)

## Upload the log messages by `:redir` and `:message` (if errored)
無し
