### ISSUE TITLE
dependsしているプラグインが読み込まれていない状態でもhook_sourceが読みこまれる

### ISSUE THREAD

**Issue by mirachan010** [Shougo/dein.vim#449]
**Warning: I will close the bug issue without the minimal init.vim and the
reproduce ways.**

# Problems summary
ddc.vimのdependsに設定したpum.vim が読みこまれない様に設定にしたときddc.vimが読みこまれて欲しくないが、hook_sourceが発動してしまう

## Expected
pum.vimが読みこまれない場合、pum.vimをdependsで設定しているddc.vimのhook_sourceが読みこまれてほしくない。

## Environment Information (Required!)

- dein.vim version(SHA1):ff8ecab

- OS:Windows11 Ubuntu(wsl) 両方で確認

- Vim/neovim version:8.2.4576

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:dein_dir = DEINPATH

set runtimepath^= DEINPATH

if dein#load_state(s:dein_dir)
  let s:dein_lazy_toml   = s:dein_dir . '01dein.toml'
  call dein#begin(s:dein_dir)
  call dein#load_toml(s:dein_lazy_toml, {'lazy': 1})
  call dein#end()
  call dein#save_state()
endif
if dein#check_install()
  call dein#install()
endif
let s:removed_plugins = dein#check_clean()
call dein#remote_plugins()

filetype plugin indent on
syntax enable
```
```toml
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
on_event = ['InsertEnter']
hook_source ='''
set nu
'''

[[plugins]]
repo = 'Shougo/pum.vim'
if='has("nvim")'
[[plugins]]
repo = 'vim-denops/denops.vim'
```
## The reproduce ways from Vim starting (Required!)

1. 起動する
2. おとす
4. 起動する
5. pum.vimがif='has("nvim")'により起動しないためddcが読み込まれないはず
6. Insertに入るとhook_sourceが発動しset nuが発動する

## Screen shot (if possible)
無し

## Upload the log messages by `:redir` and `:message` (if errored)
無し
