### ISSUE TITLE
dein doesn't build vimproc automatically

### ISSUE THREAD

**Issue by PaBLoX-CL** [Shougo/dein.vim#7]
I'm almost sure I didn't see  anything in the documentation, but I'm curious because you actually have it in your dotfiles.

I'm trying to install vimproc, and build it, but:

```vim
call dein#add('Shougo/vimproc.vim',   {'build': 'make'})
```
nor the following on a toml file works:
```toml
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
```

Is the function hasn't implemented yet, or I'm missing something?
