### ISSUE TITLE
Lazy loading error, case of use as parameter

### ISSUE THREAD

**Issue by ryunix** [Shougo/dein.vim#87]
# Problems summary

遅延ロードを設定したプラグインを引数に与える場合、正常にロードされない。

## Environment Information

* OS: OS X v10.9 Mavericks
* Vim version: 7.4.1714

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible
set runtimepath^=~/sample/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/sample/dein'))

call dein#add('thinca/vim-prettyprint', {'on_cmd' : 'PP'})
call dein#add('tyru/capture.vim')

call dein#end()

filetype plugin indent on
```

## The reproduce ways from Vim starting (Required!)

0. let g:dict = {}
0. Capture PP g:dict  " => error

既にロードされている場合は、正常となる。

0. call dein#source('vim-prettyprint')
0. let g:dict = {}
0. Capture PP g:dict  " => {}

## Upload the log messages by `:redir` and `:message`

```
capture: 'PP g:dict' caused an error: Vim(redir):E121: Undefined variable: output
Error detected while processing function capture#__cmd_capture_stub__[6]..<SNR>25_cmd_capture:
line   28:
E121: Undefined variable: res
```

**Comment by Shougo** [comment]
capture.vim 側の仕様だと思います。
遅延ロードされたコマンドの実行に対応していないのでしょう。こちらでは対応不能です。

**Comment by ryunix** [comment]
回答ありがとうございました。

**Comment by delphinus35** [comment]
これ、いろいろ試したのですが、次のように書けば対応可能です。

```toml
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']
on_source = ['capture.vim']

[[plugins]]
repo   = 'tyru/capture.vim'
on_cmd = ['Capture']
```

```vim
:Capture PP {'hoge': 'fuga'}
```

とやって動きます。
